# Generated by Django 3.1.7 on 2021-05-13 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0002_bill'),
    ]

    operations = [
        migrations.CreateModel(
            name='funds',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Member_id', models.IntegerField()),
                ('fund', models.FloatField()),
            ],
        ),
    ]
