# Generated by Django 3.1.7 on 2021-05-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0003_funds'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_tags',
            field=models.CharField(default=None, max_length=1000, null=True),
        ),
    ]
