# Generated by Django 3.1.7 on 2021-05-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0005_products_product_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='Member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.members'),
        ),
        migrations.AlterField(
            model_name='order_products',
            name='Member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.members'),
        ),
        migrations.AlterField(
            model_name='order_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.products'),
        ),
    ]
