# Generated by Django 3.1.7 on 2021-05-29 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0008_auto_20210529_1833'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='product_cmt',
            new_name='product_note',
        ),
        migrations.AlterField(
            model_name='product_cmt',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.products'),
        ),
    ]
