# Generated by Django 3.1.7 on 2021-05-29 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0010_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('userName', models.CharField(max_length=100)),
                ('passWord', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
