# Generated by Django 3.1.7 on 2021-05-29 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0011_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='processing', max_length=100)),
                ('Address_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.address')),
                ('Employee_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.employee')),
                ('bill_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pools.bill')),
            ],
        ),
    ]
