# Generated by Django 3.1.7 on 2021-06-12 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0012_shipping'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Members',
            new_name='Customer',
        ),
    ]
