# Generated by Django 3.1.7 on 2021-06-13 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pools', '0015_products_item_fk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='item_fk',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
